title: Omar Guerrero
description: Página del Dr. Omar Guerrero Orozco (1946-2023), investigador seminal de la ciencia de la administración pública.
theme: just-the-docs

url: https://omarguerrero.org

#aux_links:
#  Template Repository: https://omarguerrer.github.io

imagesurl: "/imagenes/portadas/completas/"
thumbsurl: "/imagenes/portadas/thumbs/"
